### ISSUE TITLE
Erros de português na página contato

### ISSUE THREAD

**Issue by LeandroPereiraDaCruz** [eliasportela/cod-lista-ccb#1]
Existem alguns erros de português na página
https://listaccb.com/web/contato

![image](https://user-images.githubusercontent.com/12190451/32992690-c314b988-cd34-11e7-89f5-d0a9fc4f89ee.png)

**Comment by eliasportela** [comment]
Vou providenciar a correção.

**Comment by LeandroPereiraDaCruz** [comment]
Eu já estou fazendo

**Comment by LeandroPereiraDaCruz** [comment]
Aliás já fiz

**Comment by LeandroPereiraDaCruz** [comment]
Vou te mandar já

**Comment by eliasportela** [comment]
Perfeito!

**Comment by eliasportela** [comment]
para mobile ele redireciona para ''https://listaccb.com/app/#/' não sei se viu.

**Comment by LeandroPereiraDaCruz** [comment]
Você sabe como faz pra eu ter permissão de colocar eu mesmo como assignee da issue?
Sendo assim a gente sabe quem tá resolvendo qual issue.

**Comment by LeandroPereiraDaCruz** [comment]
Hum! legal

**Comment by eliasportela** [comment]
Vix no git eu to sabendo só o basico msm
se o irmão souber me explica depois
